package usage

const EVENT_SWITCH_PAGE = "EVENT_SWITCH_PAGE"
const NEW_AGENT = "NEW_AGENT"
const NEW_TARGET = "NEW_TARGET"
const APP_STARTED = "APP_STARTED"
const APP_STOPPED = "APP_STOPPED"
const AUTH_TOKEN_UNSET = "AUTH_TOKEN_UNSET"
const PANIC = "PANIC"
const DB_ACTION = "DB_ACTION"
