# This workflow will build a golang project and create a release with a zip file
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "production" ]
    tags: [ "v*.*.*" ] # Added to trigger releases on tag pushes
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install libx11-dev
      run: sudo apt update && sudo apt install -y libx11-dev libxrandr-dev libxcursor-dev xorg-dev libxkbcommon-dev

    - name: Build
      run: sh prod-build.sh

    - name: Upload export directory as artifact
      uses: actions/upload-artifact@v4
      with:
        name: XENA_Beta
        path: export/

    # Release steps only run on tag push
    - name: Create zip file
      if: startsWith(github.ref, 'refs/tags/v') # Only runs on tag push
      run: |
        cd export
        zip -r ../XENA_Beta.zip .
        cd ..

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v') # Only runs on tag push
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }} # e.g., v1.0.0
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Zip to Release
      if: startsWith(github.ref, 'refs/tags/v') # Only runs on tag push
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./XENA_Beta.zip
        asset_name: XENA_Beta-${{ github.ref_name }}.zip
        asset_content_type: application/zip
