# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.1'

    - name: Install libx11-dev
      run: sudo apt update && sudo apt install -y libx11-dev libxrandr-dev libxcursor-dev xorg-dev libxkbcommon-dev

    - name: Build
      run: sh prod-build.sh

    - name: Upload export directory as artifact
      uses: actions/upload-artifact@v4
      with:
        name: export-files
        path: export/
